### ISSUE TITLE
Cannot convert to package.json

### ISSUE THREAD

**Issue by geekrepos** [praveenyadv/unpackage#1]
I tried to convert my package-lock,json to package.json. However I already had package.json, but when I compared it with the converted version, it was different. Even the name of the project was changed.

I am attaching a screenshot.

![image](https://user-images.githubusercontent.com/53126714/70379968-35e25d80-195a-11ea-9916-a395ec8f4167.png)

**Comment by pravnyadv** [comment]
So first, when i created this repo, my usecase was to allow people who forgot to do npm init before started the project. In that case there is no package.json created  so i considered, people will use it when they didn't do npm init to start there project and they need the package.json when they need to push the same code to production.

Now the difference in name is because i thought there would be no name, (cause no init, - i will fix this ) and The difference in the packages you see is because some dependencies are sub dependencies of other packages when u actually run npm install with this package.json you will get all the packages listed on your original package.json
